# Module 1 - Lab Exercises

### Understanding Structured Data

In [1]:
# List five different structured data formats discussed in Chapter 1.
# Store them in a Python list called `structured_data_formats`.
# Show the notebook reader that list
structured_data_formats = [
    "Tabular data (e.g., CSV, Excel, SQL tables)",
    "Multidimensional arrays (e.g., NumPy arrays)",
    "Multiple related tables (e.g., relational databases with primary/foreign keys)",
    "Time series data (e.g., indexed by timestamps)",
    "Feature-extracted data (e.g., word frequency tables)"
]
structured_data_formats

['Tabular data (e.g., CSV, Excel, SQL tables)',
 'Multidimensional arrays (e.g., NumPy arrays)',
 'Multiple related tables (e.g., relational databases with primary/foreign keys)',
 'Time series data (e.g., indexed by timestamps)',
 'Feature-extracted data (e.g., word frequency tables)']

### Installing Python Packages

In [2]:
# Import the following packages into your notebook using standard conventions:
# numpy, pandas, matplotlib, seaborn, scipy, scikit-learn, statsmodels
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
import sklearn
import statsmodels as sm

In [3]:
# For any one of the packages above, print a sentence that describes what it does
print("NumPy: Provides efficient numerical computing with multi-dimensional arrays and mathematical functions.")
print("pandas: A powerful library for data manipulation and analysis using DataFrames and Series.")
print("matplotlib: The fundamental library for creating static, animated, and interactive visualizations in Python.")
print("seaborn: A high-level statistical data visualization library built on matplotlib, making charts more visually appealing.")
print("SciPy: A scientific computing library that extends NumPy with modules for optimization, integration, and statistics.")
print("scikit-learn: A widely used machine learning library for classification, regression, clustering, and more.")
print("statsmodels: A statistical modeling library providing implementations of various statistical tests and models.")

NumPy: Provides efficient numerical computing with multi-dimensional arrays and mathematical functions.
pandas: A powerful library for data manipulation and analysis using DataFrames and Series.
matplotlib: The fundamental library for creating static, animated, and interactive visualizations in Python.
seaborn: A high-level statistical data visualization library built on matplotlib, making charts more visually appealing.
SciPy: A scientific computing library that extends NumPy with modules for optimization, integration, and statistics.
scikit-learn: A widely used machine learning library for classification, regression, clustering, and more.
statsmodels: A statistical modeling library providing implementations of various statistical tests and models.


### Interacting with the Command Line in a Notebook

In [4]:
# Write code that mimics interacting with the command line
# to check which version of python is installed.
!python --version

Python 3.11.11


In [5]:
# Write code that checks the list of items in the current directory you are in
!ls

sample_data


In [6]:
# Print a statement that describes what the output is referencing
print("The output is referencing a folder in Colab titled, sample_data. It contains six demo data files.")

The output is referencing a folder in Colab titled, sample_data. It contains six demo data files.


### NumPy Basics

In [7]:
# Create a 1D NumPy array of the first 10 natural numbers.
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 10])
# OR
array = np.arange(1, 11)
# OR
array = np.array(list(range(1, 11)))
# OR
array = np.linspace(1, 10, 10, dtype=int)
# OR
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# Print the 3rd and 7th element of the array you just created
print(array[2], array[6])

3 7


In [9]:
# Create a 1D numpy array that contains all even numbers up to 10,000
even_numbers = np.arange(2, 10001, 2)
# OR
even_numbers = np.linspace(2, 10000, 5000, dtype=int)
# OR
even_numbers = np.array([x for x in range(2, 10001, 2)])
even_numbers

array([    2,     4,     6, ...,  9996,  9998, 10000])

In [10]:
# Create a 2D numpy array where one array contains all evens up to 1,000
# and the second array contains the square of the first array.

# Create the first array (even numbers up to 1,000)
evens = np.arange(2, 1001, 2)

# Create the second array (square of the even numbers)
squares = evens ** 2

# Stack them into a 2D array (2 rows, N columns)
result = np.vstack([evens, squares])
# OR
result = np.column_stack((evens, squares))  # Creates a (500, 2) array

result

array([[      2,       4],
       [      4,      16],
       [      6,      36],
       [      8,      64],
       [     10,     100],
       [     12,     144],
       [     14,     196],
       [     16,     256],
       [     18,     324],
       [     20,     400],
       [     22,     484],
       [     24,     576],
       [     26,     676],
       [     28,     784],
       [     30,     900],
       [     32,    1024],
       [     34,    1156],
       [     36,    1296],
       [     38,    1444],
       [     40,    1600],
       [     42,    1764],
       [     44,    1936],
       [     46,    2116],
       [     48,    2304],
       [     50,    2500],
       [     52,    2704],
       [     54,    2916],
       [     56,    3136],
       [     58,    3364],
       [     60,    3600],
       [     62,    3844],
       [     64,    4096],
       [     66,    4356],
       [     68,    4624],
       [     70,    4900],
       [     72,    5184],
       [     74,    5476],
 

### Pandas DataFrame

In [11]:
# Create a pandas DataFrame with two columns: 'Name' and 'Age',
# with at least three entries, and using dictionaries to populate the columns.
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],  # List of names
    'Age': [25, 30, 22]  # Corresponding ages
}
df = pd.DataFrame(data)
df

,Name,Age
0,Alice,25
1,Bob,30
2,Charlie,22


In [12]:
# Create a pandas DataFrame with two columns: 'Name' and 'Age',
# with at least three entries, and using lists to populate the columns.

# Define lists separately
names = ['Alice', 'Bob', 'Charlie']
ages = [25, 30, 22]

# Create DataFrame using lists
df = pd.DataFrame([names, ages]).T  # Transpose to get correct shape
df.columns = ['Name', 'Age']  # Assign column names
df

,Name,Age
0,Alice,25
1,Bob,30
2,Charlie,22


In [13]:
# Select the age of the second person in the dataframe you created
df.iloc[1, 1]

30

In [14]:
# Select the name of the last person in the dataframe you created
df.iloc[-1, 0]

'Charlie'

### Simple functions

In [15]:
# Write a simple function that adds two numbers together with proper
# documentation. Demonstrate its use.
def add_numbers(num1, num2):
  """
  Add two numbers together

  Returns
  ------
  the_sum : type of arguments
  """
  return num1 + num2

add_numbers(77, 1224)

1301

In [16]:
# Write a simple function that multiplies two numbers
# together with proper documentation. Demonstrate its use.
def multiply_numbers(num1, num2):
  """
  Multiplies two numbers together

  Returns
  ------
  the_product : type of arguments
  """
  return num1*num2

multiply_numbers(77, 1224)

94248

In [17]:
# Write a simple function called 'integer_division' that
# divides a number but returns only the
# whole integer value, not any fractional remainder.
# Demonstrate its use with 10 divided by 3, and 25 divided by 4.
def integer_division(a, b):
    """
    Divides two numbers but returns only the whole integer value.

    Returns
    ------
    quotient : type of arguments
    """
    return a // b  # Floor division operator discards the remainder

result = integer_division(10, 3)
print(result)  # Expected output: 3

result = integer_division(25, 4)
print(result)  # Expected output: 6

3
6


In [18]:
# Raise the output of integer_division for 25 divided by 4 to the third power
# and store it as a new object called "new_result".
# Show in code how you'd test whether new_result equals 260.
new_result = result**3
new_result == 260

False

### List Interactions

In [19]:
mixed_list = [42, 3.14, "Hello", True, [1, 2, 3]]
mixed_list

[42, 3.14, 'Hello', True, [1, 2, 3]]

In [20]:
# Add three more items to that list
mixed_list.append("20")
mixed_list.append(109.3)
mixed_list.append(False)
mixed_list

[42, 3.14, 'Hello', True, [1, 2, 3], '20', 109.3, False]

In [21]:
# Print the data type for the fifth and last element in the list
print(type(mixed_list[4]), type(mixed_list[-1]))

<class 'list'> <class 'bool'>


In [22]:
# Prove whether your list is iterable
def isiterable(obj):
  try:
    iter(obj)
    return True
  except TypeError:
    return False

isiterable(mixed_list)

True

In [23]:
# Write a for loop that iterates through the list you created
# and prints the data type for every element in the list
for item in mixed_list:
    print(f"Value: {item}, Type: {type(item)}")

Value: 42, Type: <class 'int'>
Value: 3.14, Type: <class 'float'>
Value: Hello, Type: <class 'str'>
Value: True, Type: <class 'bool'>
Value: [1, 2, 3], Type: <class 'list'>
Value: 20, Type: <class 'str'>
Value: 109.3, Type: <class 'float'>
Value: False, Type: <class 'bool'>


In [24]:
# Create a list of squares of even numbers between 1 and 20 using list comprehension.
squares = [x**2 for x in range(1, 21) if x % 2 == 0]
squares

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400]

### Advanced: Tying some things together

In [25]:
# Create a dataframe with 10 rows and three columns.
# The first column should be a sequence of dates between today and ten days from today.
# The second column should be the number of trials run during an ABA session.
#   - Use a random draw from a Gaussian distribution averageing 60
#     with a standard deviation of 10
# The third column should be the percentage of trials with correct responding.
#   - Use a random draw from uniform distribution with a low of 0 and high of 100.

# Generate a sequence of 10 dates starting from today
date_range = pd.date_range(start=pd.Timestamp.today().normalize(), periods=10, freq='D')

# Generate the number of trials using a Gaussian distribution (mean=60, std=10)
num_trials = np.random.normal(loc=60, scale=10, size=10).astype(int)  # Convert to integers

# Generate the percentage of correct responses using a uniform distribution (0 to 100%)
percent_correct = np.random.uniform(low=0, high=100, size=10)

# Create the DataFrame
df = pd.DataFrame({
    'Date': date_range,
    'Num_Trials': num_trials,
    'Percent_Correct': percent_correct
})
df

,Date,Num_Trials,Percent_Correct
0,2025-02-01,47,31.282445
1,2025-02-02,54,67.181805
2,2025-02-03,63,49.745554
3,2025-02-04,59,77.497899
4,2025-02-05,76,93.552086
5,2025-02-06,65,63.688165
6,2025-02-07,48,29.362892
7,2025-02-08,42,43.195872
8,2025-02-09,48,17.026042
9,2025-02-10,45,21.825911
