## Module 3 - Lab Exercises

In [4]:
# Create a NumPy array from a list of integers: [1, 2, 3, 4, 5] 
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Print the shape and data type of the array you created.
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)
print(arr.dtype)

(5,)
int64


In [6]:
# Create a 2D NumPy array called "arr2d" from [[1.5, -0.1, 3], [0, -3, 6.5]] and print it
arr2d = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print(arr2d)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]


In [7]:
# Multiply every element in arr2d by 10
arr2d = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
arr2d * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [8]:
# Create a 3x3 array of zeros
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Create a 4x2 array of ones with dtype int
ones = np.ones((4, 2), dtype=int)
print(ones)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [10]:
# Create a NumPy array containing numbers from 0 to 14
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [11]:
# Retrieve the element at index 3 from an array called "arr" 
# and where "arr" is created using np.arange(10).
arr = np.arange(10)
print(arr[3])

3


In [12]:
# Slice the first five elements of arr
arr = np.arange(10)
print(arr)
print(arr[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [13]:
# Return only the values greater than 5 from arr.
arr = np.arange(10)
print(arr[arr > 5])

[6 7 8 9]


In [14]:
# Create a 4x4 array of random numbers from a standard normal distribution
arr = np.random.randn(4, 4)
print(arr)

[[1.31625188 1.0826382  0.94033555 1.10559313]
 [0.83633862 0.06919059 1.49672691 0.43903487]
 [0.99253195 0.01272658 0.37952835 0.08950961]
 [1.18963943 0.40569719 0.25498139 0.31269811]]


In [15]:
# Create an array and divide all elements by 2
arr = np.array([15, 30, 45, 60, 75])
print(arr/ 2)

[ 7.5 15.  22.5 30.  37.5]


In [16]:
arr = np.arange(15). reshape(3, 5)
print(arr)

print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [17]:
# Find the element-wise maximum between [3, 7, 2] and [5, 2, 9]
arr1 = np.array([3, 7, 2])
arr2 = np.array([5, 2, 9])
print(np.maximum(arr1, arr2))

[5 7 9]


In [18]:
# Create a 4x4 array filled with random values 
# from the standard normal distribution
# Replace all negative values in the created array with 0
arr = np.random.rand(4, 4)
print("Orignal array:")
print(arr)
arr[arr < 0] = 0
print("\nAfter replacing negatives with 0:")
print(arr)

Orignal array:
[[0.66801489 0.27230898 0.39368279 0.02813194]
 [0.23443587 0.49947321 0.06424659 0.40953844]
 [0.74971419 0.67177272 0.15460937 0.30649454]
 [0.14148185 0.16374108 0.26408871 0.94286449]]

After replacing negatives with 0:
[[0.66801489 0.27230898 0.39368279 0.02813194]
 [0.23443587 0.49947321 0.06424659 0.40953844]
 [0.74971419 0.67177272 0.15460937 0.30649454]
 [0.14148185 0.16374108 0.26408871 0.94286449]]


In [19]:
# Compute the cumulative sum of [1, 2, 3, 4, 5]
arr = np.array([1, 2, 3, 4, 5])
print(np.cumsum(arr))

[ 1  3  6 10 15]


In [20]:
# Sort a randomly generated 1D array of size 10
arr = np.random.rand(10)
print("Original:")
print(arr)
print("\nSorted array:")
print(np.sort(arr))

Original:
[0.21837443 0.10290862 0.54114185 0.8327922  0.07078293 0.24481307
 0.17785585 0.01421059 0.63216804 0.83599975]

Sorted array:
[0.01421059 0.07078293 0.10290862 0.17785585 0.21837443 0.24481307
 0.54114185 0.63216804 0.8327922  0.83599975]


In [21]:
# Find unique values in [1, 2, 3, 1, 2, 4, 5]
arr = np.array([1, 2, 3, 1, 2, 4, 5])
print(np.unique(arr))

[1 2 3 4 5]


In [22]:
# Generate a 5x5 matrix of random integers between 10 and 50
arr = np.random.randint(10, 51,(5, 5))
print(arr)

[[49 31 14 42 12]
 [21 22 16 23 46]
 [22 29 40 48 37]
 [38 49 48 11 20]
 [16 31 24 47 37]]


In [23]:
# Count how many positive numbers exist in a random 10-element array
arr = np.random.randn(10)
print(arr)
print("\nCount of positive numbers:", np.sum(arr > 0))

[ 1.22393077  0.89999087  1.0353969  -0.54262227 -1.77844237  1.20686128
 -1.40492112 -0.1167217  -1.02821682  0.74230179]

Count of positive numbers: 5


In [24]:
# Add a 1D array [1, 2, 3] to each row of a 3x3 matrix of ones
matrix = np.ones((3, 3), dtype = int)
arr = np.array([1, 2, 3])
print("Matrix:")
print(matrix)
print("\n1D array:", arr)
print("\nResult:")
print(matrix + arr)

Matrix:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

1D array: [1 2 3]

Result:
[[2 3 4]
 [2 3 4]
 [2 3 4]]


In [25]:
# Swap axes of a 2x3 array
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
print("Original array (2x3):")
print(arr)
print(arr.swapaxes(0, 1))

Original array (2x3):
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [26]:
# Select rows at indices [1, 3, 5] from a 6x4 matrix
matrix = np.random.randint(1, 51, (6, 4))
print("\nSelected rows at indices [1, 3, 5]:")
print(matrix[[1, 3, 5]])


Selected rows at indices [1, 3, 5]:
[[48 13 46 46]
 [15 25  5 44]
 [49  5  2 32]]


In [27]:
# Set all elements greater than 5 in a random array to -1
arr = np.random.randint(1, 11,10)
print(arr)
arr[arr > 5] = -1
print("\nAfter setting elements > 5 to -1:")
print(arr)

[6 9 9 6 8 4 4 3 3 9]

After setting elements > 5 to -1:
[-1 -1 -1 -1 -1  4  4  3  3 -1]


In [28]:
# Compute the square root of all elements in np.arange(10)
arr = np.arange(10)
print("original array:")
print(arr)
print("\nSquare root of each element:")
print(np.sqrt(arr))

original array:
[0 1 2 3 4 5 6 7 8 9]

Square root of each element:
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [29]:
# Reshape a 1D array of 12 elements into a 3x4 matrix
arr = np.random.randn(12)
print("\nReshaped to 3 x 4 matrix:")
print(arr.reshape(3, 4))


Reshaped to 3 x 4 matrix:
[[-1.54443318  0.83930145 -0.70137377 -1.34948581]
 [-0.29904486 -0.96761052  1.18510714 -1.20884066]
 [ 1.5876283  -0.51420553 -0.2346076  -0.33772063]]


In [30]:
# Compute the dot product of two 3x3 matrices filled with ones
A = np.ones((3, 3))
B = np.ones((3, 3))
print(np.dot(A, B))

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [31]:
# Check which values in [1, 2, 3, 4, 5] are greater than 3
arr = np.array([1, 2, 3, 4, 5])
print(arr > 3)

[False False False  True  True]


In [32]:
# Draw 5 samples from a normal distribution with mean=10, std=2
samples = np.random.normal(10, 2, 5)
print(samples)

[7.44227489 8.69015902 9.61431752 7.81417104 6.04429904]


In [33]:
# Sum across axis 1 for a 4x5 random array
arr = np.random.randint(1, 11, (4, 5))
print("\nSum across axis 1 (row-wise):")
print(arr.sum(axis=1))


Sum across axis 1 (row-wise):
[34 22 27 35]
