## Module 3 - Lab Exercises

In [1]:
# Create a NumPy array from a list of integers: [1, 2, 3, 4, 5]
import numpy as np
a = list(range(1,6))
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [2]:
# Print the shape and data type of the array you created.
print(arr.shape, arr.dtype)

(5,) int64


In [3]:
# Create a 2D NumPy array called "arr2d" from [[1.5, -0.1, 3], [0, -3, 6.5]] and print it
arr2d = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
arr2d

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [4]:
# Multiply every element in arr2d by 10
arr2d * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [5]:
# Create a 3x3 array of zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Create a 4x2 array of ones with dtype int
tmp = np.ones((4,2), dtype = 'int')
tmp.dtype

dtype('int64')

In [7]:
# Create a NumPy array containing numbers from 0 to 14
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
# Retrieve the element at index 3 from an array called "arr"
# and where "arr" is created using np.arange(10).
arr = np.arange(10)
arr[3]

3

In [9]:
# Slice the first five elements of arr
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
# Return only the values greater than 5 from arr.
arr[arr>5]

array([6, 7, 8, 9])

In [11]:
# Create a 4x4 array of random numbers from a standard normal distribution
np.random.standard_normal(size=(4,4))

array([[-0.92140682,  0.45216217, -2.63563421, -0.2362268 ],
       [-1.56710614, -0.11302884, -1.40313126, -0.31373243],
       [ 0.15291176,  0.78514248, -0.83828075, -1.42894857],
       [-0.39127375, -0.07292385, -0.34463955, -0.26929272]])

In [12]:
# Create an array and divide all elements by 2
arr = np.arange(1,11)
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [13]:
# Transpose a 3x5 array created using np.arange(15).reshape(3,5)
arr = np.arange(15).reshape(3,5)
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [14]:
# Find the element-wise maximum between [3, 7, 2] and [5, 2, 9]
np.max([[3,7,2],[5,2,9]])

# DJC Comment: This is the overall max. How might you get the element-wise max?

9

In [15]:
# Create a 4x4 array filled with random values
# from the standard normal distribution
# Replace all negative values in the created array with 0
arr = np.random.standard_normal(size=(4,4))
arr[arr<0] = 0
arr

array([[0.89364185, 0.        , 0.        , 0.14479522],
       [0.06923661, 0.        , 0.        , 0.36551847],
       [0.        , 0.        , 0.        , 0.        ],
       [1.69204045, 0.55050293, 0.        , 0.        ]])

In [16]:
# Compute the cumulative sum of [1, 2, 3, 4, 5]
np.cumsum([1,2,3,4,5])

array([ 1,  3,  6, 10, 15])

In [17]:
# Sort a randomly generated 1D array of size 10
arr = np.random.standard_normal(10)
arr.sort()
arr

array([-1.30697134, -1.26119219, -0.8046739 , -0.5434964 , -0.32926126,
        0.08816441,  0.24393328,  0.37985708,  1.29642059,  2.21567958])

In [18]:
# Find unique values in [1, 2, 3, 1, 2, 4, 5]
np.unique([1,2,3,1,2,4,5])

array([1, 2, 3, 4, 5])

In [19]:
# Generate a 5x5 matrix of random integers between 10 and 50
np.random.uniform(10,50,(5,5)).astype(int)

# DJC Comment: This will technically cap at 49. :-)

array([[26, 30, 38, 30, 41],
       [16, 42, 34, 24, 24],
       [14, 41, 44, 18, 46],
       [22, 48, 14, 14, 39],
       [38, 18, 40, 25, 49]])

In [20]:
# Count how many positive numbers exist in a random 10-element array
arr = np.random.standard_normal(10)
np.sum(arr>0)

8

In [21]:
# Add a 1D array [1, 2, 3] to each row of a 3x3 matrix of ones
arr1 = np.ones((3,3))
arr2 = np.array([1, 2, 3])
arr1 + arr2

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [22]:
# Swap axes of a 2x3 array
np.random.standard_normal(size=(2,3)).swapaxes(0,1)

array([[-0.06762783, -0.18730633],
       [-0.49311915,  0.16801138],
       [ 1.9595508 ,  0.127966  ]])

In [23]:
# Select rows at indices [1, 3, 5] from a 6x4 matrix
arr = np.random.standard_normal(size=(6,4))
arr[[1,3,5]]

array([[-0.02341802, -0.17051606, -0.50739171,  0.78005844],
       [-0.27171072,  0.27916216, -0.31556511, -1.88586715],
       [-2.43551661, -1.07447239,  0.76617843, -0.6754435 ]])

In [24]:
# Set all elements greater than 5 in a random array to -1
arr = 5 * np.random.standard_normal(size=(5,5))
arr[arr>5] = -1
arr

array([[ -2.45116984, -11.32218171,  -3.35390266,  -1.        ,
         -1.        ],
       [  4.64632062,   4.57841691,  -1.09676679,   0.6640411 ,
          0.9732772 ],
       [ -0.94066514,  -3.56833621,   4.25592986,  -4.40990292,
         -8.38991039],
       [ -8.97997408,   1.54584088,   0.41563097,  -1.        ,
         -1.        ],
       [  1.13101322,  -0.53738045,   1.86074716,  -0.34140279,
          3.89253737]])

In [25]:
# Compute the square root of all elements in np.arange(10)
np.sqrt(np.arange(10))

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [26]:
# Reshape a 1D array of 12 elements into a 3x4 matrix
np.random.standard_normal(12).reshape(3,4)

array([[-0.81528014,  1.46672603,  1.38264037, -0.25241975],
       [ 0.33658434,  1.67742032,  0.2596464 , -1.99809709],
       [ 0.40655369, -0.2044568 , -0.01494138, -1.32615049]])

In [27]:
# Compute the dot product of two 3x3 matrices filled with ones
# np.dot(np.ones((3,3)).T,np.ones((3,3)))
np.ones((3,3)).T @ np.ones((3,3))

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [28]:
# Check which values in [1, 2, 3, 4, 5] are greater than 3
np.arange(1,6) > 3

array([False, False, False,  True,  True])

In [29]:
# Draw 5 samples from a normal distribution with mean=10, std=2
np.random.standard_normal(5) * 2 + 10

array([ 6.19887514, 12.42354732,  7.8651427 , 10.97549062, 10.68671244])

In [30]:
# Sum across axis 1 for a 4x5 random array
np.sum(np.random.standard_normal(size=(4,5)),axis=1)

array([ 0.0929806 , -0.06624904, -0.16087829, -1.82785311])