## Module 3 - Lab Exercises

In [1]:
# Create a NumPy array from a list of integers: [1, 2, 3, 4, 5]
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
# Print the shape and data type of the array you created.
print(arr.shape)
print(arr.dtype)

(5,)
int64


In [3]:
# Create a 2D NumPy array called "arr2d" from [[1.5, -0.1, 3], [0, -3, 6.5]] and print it
arr2d = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print(arr2d)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]


In [4]:
# Multiply every element in arr2d by 10
arr2d * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [5]:
# Create a 3x3 array of zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Create a 4x2 array of ones with dtype int
four_two = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=int)
print(four_two.dtype)

int64


In [7]:
# Create a NumPy array containing numbers from 0 to 14
fourteen = np.arange(0,15)
print(fourteen)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
# Retrieve the element at index 3 from an array called "arr"
# and where "arr" is created using np.arange(10).
arr = np.arange(10)
arr[3]

3

In [9]:
# Slice the first five elements of arr
arr[:5]

array([0, 1, 2, 3, 4])

In [10]:
# Return only the values greater than 5 from arr.
hi5 = arr[arr > 5]
hi5

array([6, 7, 8, 9])

In [11]:
# Create a 4x4 array of random numbers from a standard normal distribution
frfr = np.random.normal(size=(4,4))
frfr

# DJC COMMENT: Also, np.random.standard_normal((4,4))

array([[ 0.51224683, -0.50590417,  1.20038793, -0.40366776],
       [ 0.03317891,  0.24509125, -0.71517145, -0.53948511],
       [-0.24073135,  0.99236279,  0.70132619,  0.32491607],
       [-0.86556502,  0.07508926, -0.38183578, -1.49461683]])

In [12]:
# Create an array and divide all elements by 2
arr2d = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
#print(arr2d)
halfies = arr2d / 2
print(halfies)

[[ 0.75 -0.05  1.5 ]
 [ 0.   -1.5   3.25]]


In [13]:
# Transpose a 3x5 array created using np.arange(15).reshape(3,5)
#arr3 = np.arange((3,5))
arr3 = np.arange(15).reshape(3,5)
arr3
tr_arr3 = arr3.T
tr_arr3

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [14]:
# Find the element-wise maximum between [3, 7, 2] and [5, 2, 9]
xy = np.array([[3, 7, 2],[5, 2, 9]])
xy
xy.max() # <----- DJC Comment: This is the overall max. What is the max of each element?

9

In [15]:
# Create a 4x4 array filled with random values
# from the standard normal distribution
# Replace all negative values in the created array with 0
xyyy = np.random.normal(size=(4,4)) # DJC Comment: Also, np.random.standard_normal((4,4))
xyyy
xyyy_noneg = np.where(xyyy < 0, 0, xyyy)
xyyy_noneg

array([[0.        , 0.        , 0.37720938, 0.        ],
       [0.90862619, 0.08934452, 0.        , 0.        ],
       [0.74674178, 0.        , 0.35032637, 0.96967778],
       [0.        , 0.        , 0.        , 0.        ]])

In [16]:
# Compute the cumulative sum of [1, 2, 3, 4, 5]
z = np.array([1, 2, 3, 4, 5])
z.cumsum()

array([ 1,  3,  6, 10, 15])

In [17]:
# Sort a randomly generated 1D array of size 10
r = np.random.rand(10)
r.sort()
r

array([0.09254307, 0.23103927, 0.32545776, 0.39142138, 0.4632603 ,
       0.56386562, 0.68451653, 0.7670577 , 0.7687713 , 0.8614784 ])

In [18]:
# Find unique values in [1, 2, 3, 1, 2, 4, 5]
u = np.array([1, 2, 3, 1, 2, 4, 5])
np.unique(u)

array([1, 2, 3, 4, 5])

In [19]:
# Generate a 5x5 matrix of random integers between 10 and 50
tf = np.random.randint(10,50, size=(5,5)) # DJC Comment: This caps at 49. :-)
tf

array([[11, 48, 29, 23, 15],
       [33, 16, 25, 40, 31],
       [43, 28, 18, 37, 11],
       [39, 38, 40, 41, 23],
       [35, 40, 49, 25, 13]])

In [20]:
# Count how many positive numbers exist in a random 10-element array
p = np.random.rand(10)
sum(p>0)
#np.where(p>0)

10

In [21]:
# Add a 1D array [1, 2, 3] to each row of a 3x3 matrix of ones
onearr = np.array([1, 2, 3])
onearr
addthree = np.ones((3,3))
addthree
z = addthree + onearr

print(z)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [22]:
help(np.swapaxes) # DJC Comment: Nice!

Help on _ArrayFunctionDispatcher in module numpy:

swapaxes(a, axis1, axis2)
    Interchange two axes of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis1 : int
        First axis.
    axis2 : int
        Second axis.
    
    Returns
    -------
    a_swapped : ndarray
        For NumPy >= 1.10.0, if `a` is an ndarray, then a view of `a` is
        returned; otherwise a new array is created. For earlier NumPy
        versions a view of `a` is returned only if the order of the
        axes is changed, otherwise the input array is returned.
    
    Examples
    --------
    >>> x = np.array([[1,2,3]])
    >>> np.swapaxes(x,0,1)
    array([[1],
           [2],
           [3]])
    
    >>> x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
    >>> x
    array([[[0, 1],
            [2, 3]],
           [[4, 5],
            [6, 7]]])
    
    >>> np.swapaxes(x,0,2)
    array([[[0, 4],
            [2, 6]],
           [[1, 5],
            [3, 7]]])



In [23]:
# Swap axes of a 2x3 array
b = np.array(([2, 3, 1], [4, 5, 6]))
# dir shows you all options and next line is an easy search for methods
#dir(b)
#[i for i in dir(b) if 'swap' in i]
c = np.swapaxes(b,1,0)
print(c)

[[2 4]
 [3 5]
 [1 6]]


In [24]:
# Select rows at indices [1, 3, 5] from a 6x4 matrix
# new line for each row for readiability
d = np.array((
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [4, 5, 6, 7],
    [5, 6, 7, 8],
    [6, 7, 8, 9]
    ))
d[[1, 3, 5]]

array([[2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [25]:
# Set all elements greater than 5 in a random array to -1
e = np.random.randint(0,20, size=(1,5))
e
f = np.where(e > 5, -1, e)
f

array([[-1,  2, -1, -1,  3]])

In [26]:
# Compute the square root of all elements in np.arange(10)
g = np.arange(10)
np.sqrt(g)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [27]:
# Reshape a 1D array of 12 elements into a 3x4 matrix
h = np.arange(12)
hh = h.reshape(3,4)
hh

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
# Compute the dot product of two 3x3 matrices filled with ones
ab = np.ones((3,3))
bc = np.ones((3,3))
ab.dot(bc)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [33]:
# Check which values in [1, 2, 3, 4, 5] are greater than 3
de = np.array([1, 2, 3, 4, 5])
print(np.where(de > 3))

# DJC Comment: Also,
de >3

(array([3, 4]),)


array([False, False, False,  True,  True])

In [30]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the `~numpy.random.Generator.normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
     

In [35]:
# Draw 5 samples from a normal distribution with mean=10, std=2
print(np.random.normal(10, 2, size=(5)))

# DJC Comment: Technically, you don't need parens around the size parameter
print(np.random.normal(10, 2, size=5))

[11.95243428  9.69301002  9.61833466  6.27288829 10.32649609]
[10.06359369  5.9818821   6.6768144  11.28463949 10.33275596]


In [32]:
# Sum across axis 1 for a 4x5 random array
gh = np.random.rand(4,5)
gh
hj = gh.cumsum(axis=1) # DJC Comment: Is cumsum the same as sum?
print(hj)

[[0.35874399 0.44196326 0.70535816 1.49709317 2.02900848]
 [0.82239311 1.59446656 2.26571196 3.11463086 4.06861068]
 [0.16356512 0.82875276 1.15225274 1.77739809 2.4945972 ]
 [0.50774138 1.08381066 1.10080757 1.56662178 2.39883015]]
