## Module 3 - Lab Exercises

In [1]:
# Create a NumPy array from a list of integers: [1, 2, 3, 4, 5]
import numpy as np
data1 = [1, 2, 3, 4, 5]
arr = np.array(data1)
print(arr)

[1 2 3 4 5]


In [2]:
# Print the shape and data type of the array you created.
data1 = [1, 2, 3, 4, 5]
arr = np.array(data1)
print(arr.shape)
print(arr.dtype)

(5,)
int64


In [3]:
# Create a 2D NumPy array called "arr2d" from [[1.5, -0.1, 3], [0, -3, 6.5]] and print it
data2 = [[1.5, -0.1, 3], [0, -3, 6.5]]
arr2d = np.array(data2)
print(arr2d)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]


In [4]:
# Multiply every element in arr2d by 10
arr2d = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
arr2d = arr2d * 10
print(arr2d)

[[ 15.  -1.  30.]
 [  0. -30.  65.]]


In [5]:
# Create a 3x3 array of zeros
arr3d = np.zeros((3, 3))
print(arr3d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
# Create a 4x2 array of ones with dtype int
arr4 = np.ones((4, 2,))
print(arr4)
arr4.dtype = 'int'
print(arr4)

# DJC COMMENT: I added the print statement on line 5 so you can see what
# line 4 is doing to your data. Here is an easier way that doesn't modify the data.
# Notice the decimal point is gone indicating the dtype is an int.
np.ones((4,2), dtype=int)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408]]


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [7]:
# Create a NumPy array containing numbers from 0 to 14
import numpy as np # <--- # DJC COMMENT: Not needed as you imported in the first cell
arr5 = np.arange(15)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
# Retrieve the element at index 3 from an array called "arr"
# and where "arr" is created using np.arange(10).
arr = np.arange(10)
#print(arr)
print(arr[3])

3


In [9]:
# Slice the first five elements of arr
arr = np.arange(10)
arr_slice = arr[0:4]
print(arr_slice)

# DJC COMMENT: This only has four elements? How would you get the first five?

[0 1 2 3]


In [10]:
# Return only the values greater than 5 from arr.
import numpy as np
arr = np.arange(10)
print(arr[arr>5])

[6 7 8 9]


In [11]:
# Create a 4x4 array of random numbers from a standard normal distribution
import numpy as np
arr_4x4 = np.random.normal(0,1, (4,4))
print(arr_4x4)

# DJC COMMENT: Also, np.random.standard_normal((4,4))

[[ 1.78893949 -1.88441654  0.04614985 -0.66096952]
 [ 0.18108153  0.60654724 -0.6002403  -0.82661463]
 [ 0.43813329  0.350349   -1.30111376 -0.03672345]
 [-0.05969743 -0.04129142 -0.56602589 -0.55958749]]


In [12]:
# Create an array and divide all elements by 2
arr = np.arange(10)
arr = arr/2
print(arr)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [13]:
# Transpose a 3x5 array created using np.arange(15).reshape(3,5)
arr = np.arange(15).reshape(3,5)
#print(arr)
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [14]:
# Find the element-wise maximum between [3, 7, 2] and [5, 2, 9]
x = np.array([3, 7, 2])
y = np.array([5, 2, 9])
print(np.maximum(x, y))

[5 7 9]


In [15]:
# Create a 4x4 array filled with random values
# from the standard normal distribution
# Replace all negative values in the created array with 0
import numpy as np
arr = np.random.normal(0,1, (4,4)) # DJC COMMENT: Also, np.random.standard_normal((4,4))
#print(arr)
arr[arr <0] = 0 # DJC COMMENT: Also, np.where(arr < 0, 0, arr)
print(arr)

[[0.16228885 0.71011231 0.         0.        ]
 [0.68586449 0.         0.03756333 0.55084466]
 [1.52879595 0.         1.31126654 0.51543073]
 [0.50551557 0.         1.92672904 0.88052422]]


In [16]:
# Compute the cumulative sum of [1, 2, 3, 4, 5]
cumulative_sum = []
running_sum = 0
numbers = [1, 2, 3, 4, 5]

for number in numbers:
    running_sum += number
    cumulative_sum.append(running_sum)
print(cumulative_sum)

# DJC COMMENT: Also,
arr = np.array([1, 2, 3, 4, 5])
arr.cumsum()

[1, 3, 6, 10, 15]


In [17]:
# Sort a randomly generated 1D array of size 10
import numpy as np # <---- # DJC COMMENT: Not needed as already imported
import random
#Generate a random 1D array of size 10
random_array = [random.randint(0, 100) for _ in range(10)]
#Sort the array
sorted_array = np.sort(random_array)
print(sorted_array)

[  2   2  14  40  40  59  69  78 100 100]


In [18]:
# Find unique values in [1, 2, 3, 1, 2, 4, 5]
a = [1, 2, 3, 1, 2, 4, 5]
unique_values = np.unique(a)
print(unique_values)

[1 2 3 4 5]


In [40]:
# Generate a 5x5 matrix of random integers between 10 and 50
matrix = np.random.randint(10, 51, size=(5, 5))
print(matrix)

[[11 30 30 31 10]
 [25 30 12 14 25]
 [12 47 12 27 12]
 [26 29 34 28 21]
 [37 37 40 24 37]]


In [37]:
# Count how many positive numbers exist in a random 10-element array
import numpy as np # <---- # DJC COMMENT: Not needed as already imported
import random # <---- # DJC COMMENT: Not needed as already imported
random_array = [random.randint(0, 100) for _ in range(10)]
#print(random_array)
count = np.sum(np.array(random_array) > 0)
print(count)

# DJC Comment: This is definitely one way to do it by making everything positive to start!
# I was thinking more of how you would find values when they might also be negative.
# For example,
arr = np.random.randn(10)
print(arr)
(arr > 0).sum()

10


In [21]:
# Add a 1D array [1, 2, 3] to each row of a 3x3 matrix of ones
import numpy as np # <---- # DJC COMMENT: Not needed as already imported
matrix_of_ones = np.ones((3, 3))
#print(matrix_of_ones)
array_to_add = np.array([1, 2, 3])
result = matrix_of_ones + array_to_add
print(result)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [22]:
# Swap axes of a 2x3 array
import numpy as np # <---- # DJC COMMENT: Not needed as already imported
matrix = np.ones((2, 3))
#print(matrix)
swapped_matrix = np.swapaxes(matrix, 0, 1)
print(swapped_matrix)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
# Select rows at indices [1, 3, 5] from a 6x4 matrix
import numpy as np # <---- # DJC COMMENT: Not needed as already imported
new_matrix = np.ones((6, 4))
#print(new_matrix)
selected_rows = new_matrix[[1, 3, 5]]
print(selected_rows)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
# Set all elements greater than 5 in a random array to -1
import numpy as np
random_array= np.random.randint(0, 10, size=10)
#print((random_array))
random_array[random_array > 5] = -1
print(random_array)

[-1  3 -1 -1  1  2  2  3  3  4]


In [25]:
# Compute the square root of all elements in np.arange(10)
another_array = np.arange(10)
#print(another_array)
sqrt_array = np.sqrt(another_array)
print(sqrt_array)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [26]:
# Reshape a 1D array of 12 elements into a 3x4 matrix
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
#print(array_1d)
matrix_3x4 = array_1d.reshape(3, 4)
print(matrix_3x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
# Compute the dot product of two 3x3 matrices filled with ones
new_matrix1 = np.ones((3, 3))
new_matrix2 = np.ones((3, 3))
print(new_matrix1)
print(new_matrix2)
dot_product = np.dot(new_matrix1, new_matrix2)
print(dot_product)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [28]:
# Check which values in [1, 2, 3, 4, 5] are greater than 3
numbers = [1, 2, 3, 4, 5]
greater_than_3 = [num for num in numbers if num > 3]
print(greater_than_3)

[4, 5]


In [29]:
# Draw 5 samples from a normal distribution with mean=10, std=2
mean = 10
std_dev = 2
samples = np.random.normal(loc=mean, scale=std_dev, size=5) # DJC Comment: Explicit! Nice!
print(samples)

[10.18416309  7.48268506  7.3686386   8.63840468 11.20278603]


In [30]:
# Sum across axis 1 for a 4x5 random array
last_array = np.random.randint(0, 10, size=(4, 5))
print(last_array)
sum_across_axis = np.sum(last_array, axis=1)
print(sum_across_axis)

[[4 2 6 1 8]
 [1 0 1 2 9]
 [7 9 4 8 8]
 [2 7 1 5 3]]
[21 13 36 18]
